USE [master]
GO

/****** Object:  Database [1ClickDemo]    Script Date: 8-9-2019 14:33:25 ******/
CREATE DATABASE [1ClickDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'1ClickDemo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.LOGGINGLOGGING\MSSQL\DATA\1ClickDemo.mdf' , SIZE = 532480KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'1ClickDemo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.LOGGINGLOGGING\MSSQL\DATA\1ClickDemo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [1ClickDemo] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [1ClickDemo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [1ClickDemo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [1ClickDemo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [1ClickDemo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [1ClickDemo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [1ClickDemo] SET ARITHABORT OFF 
GO

ALTER DATABASE [1ClickDemo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [1ClickDemo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [1ClickDemo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [1ClickDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [1ClickDemo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [1ClickDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [1ClickDemo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [1ClickDemo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [1ClickDemo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [1ClickDemo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [1ClickDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [1ClickDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [1ClickDemo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [1ClickDemo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [1ClickDemo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [1ClickDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [1ClickDemo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [1ClickDemo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [1ClickDemo] SET  MULTI_USER 
GO

ALTER DATABASE [1ClickDemo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [1ClickDemo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [1ClickDemo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [1ClickDemo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [1ClickDemo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [1ClickDemo] SET QUERY_STORE = OFF
GO

USE [1ClickDemo]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [1ClickDemo] SET  READ_WRITE 
GO


