USE [1ClickDemo]
GO

/****** Object:  Table [dbo].[DataGen]    Script Date: 15-10-2019 00:06:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DataGen](
	[QueueUUID] [nvarchar](100) NOT NULL,
	[BuildAccount] [varchar](max) NULL,
	[ERAAPIAccount] [varchar](max) NULL,
	[MoveAPIAccount] [varchar](max) NULL,
	[DataServicesIP] [varchar](max) NULL,
	[PCClusterIP] [varchar](max) NULL,
	[PCNode1IP] [varchar](max) NULL,
	[PCnode2IP] [varchar](max) NULL,
	[PCnode3IP] [varchar](max) NULL,
	[PCNode1Name] [varchar](max) NULL,
	[PCNode2Name] [varchar](max) NULL,
	[PCNode3Name] [varchar](max) NULL,
	[ERA1Name] [varchar](max) NULL,
	[ERA1IP] [varchar](max) NULL,
	[DC1IP] [varchar](max) NULL,
	[DC2IP] [varchar](max) NULL,
	[DC1Name] [varchar](max) NULL,
	[DC2Name] [varchar](max) NULL,
	[Domainname] [varchar](max) NULL,
	[Nw1name] [varchar](max) NULL,
	[Nw2name] [varchar](max) NULL,
	[MoveIP] [varchar](max) NULL,
	[Move_ImageName] [varchar](max) NULL,
	[Move_VMName] [varchar](max) NULL,
	[XRayIP] [varchar](max) NULL,
	[XRay_ImageName] [varchar](max) NULL,
	[XRay_VMName] [varchar](max) NULL,
	[DC_ImageName] [varchar](max) NULL,
	[ERA_ImageName] [varchar](max) NULL,
	[ERA_MSSQLIP] [varchar](max) NULL,
	[ERA_MSSQLName] [varchar](max) NULL,
	[ERA_MSSQLImage] [varchar](max) NULL,
	[ERA_MariaName] [varchar](max) NULL,
	[ERA_PostGName] [varchar](max) NULL,
	[EraContainerName] [varchar](max) NULL,
	[Oracle1_0Image] [varchar](max) NULL,
	[Oracle1_1Image] [varchar](max) NULL,
	[Oracle1_2Image] [varchar](max) NULL,
	[OracleIP] [varchar](max) NULL,
	[Oracle_VMName] [varchar](max) NULL,
	[KarbonContainerName] [varchar](max) NULL,
	[KarbonIP] [varchar](max) NULL,
	[SysprepPassword] [varchar](max) NULL,
	[SENAME] [varchar](max) NULL,
	[SEROLE] [varchar](max) NULL,
	[SESlackID] [varchar](max) NULL,
	[SEUPN] [varchar](max) NULL,
	[SECompany] [varchar](max) NULL,
	[EnablePulse] [varchar](max) NULL,
	[XRayVersion] [varchar](max) NULL,
	[MoveVersion] [varchar](max) NULL,
	[Filesversion] [varchar](max) NULL,
	[CALMversion] [varchar](max) NULL,
	[Karbonversion] [varchar](max) NULL,
	[Objectsversion] [varchar](max) NULL,
	[ERAVersion] [varchar](max) NULL,
	[NCCVersion] [varchar](max) NULL,
	[Files1_ImageName] [varchar](max) NULL,
	[Files2_ImageName] [varchar](max) NULL,
	[Files2IP] [varchar](max) NULL,
	[Files2VM_Name] [varchar](max) NULL,
	[FS1_IntName] [varchar](max) NULL,
	[FS1_ExtName] [varchar](max) NULL,
	[FS1IntRange] [varchar](max) NULL,
	[FS1ExtRange] [varchar](max) NULL,
	[NW1DHCPStart] [varchar](max) NULL,
	[StoragePoolName] [varchar](max) NULL,
	[ImagesContainerName] [varchar](max) NULL,
	[DisksContainerName] [varchar](max) NULL,
	[NTPServer1] [varchar](max) NULL,
	[NTPServer2] [varchar](max) NULL,
	[NTPServer3] [varchar](max) NULL,
	[NTPServer4] [varchar](max) NULL,
	[smtpSender] [varchar](max) NULL,
	[smtpport] [varchar](max) NULL,
	[smtpServer] [varchar](max) NULL,
	[IISNLBIP] [varchar](max) NULL,
	[Supportemail] [varchar](max) NULL,
	[PrivateKey] [text] NULL,
	[PublicKey] [varchar](max) NULL,
	[AvailableAOSVersion] [varchar](max) NULL,
	[ERA_MySQLName] [varchar](max) NULL,
	[Frame_WinImage] [varchar](max) NULL,
	[Frame_CCAISO] [varchar](max) NULL,
	[Frame_AgentISO] [varchar](max) NULL,
	[Frame_GoldenVMName] [varchar](max) NULL,
	[Oracle1_3Image] [varchar](max) NULL,
	[Oracle1_4Image] [varchar](max) NULL,
	[Oracle1_5Image] [varchar](max) NULL,
	[Oracle1_6Image] [varchar](max) NULL,
	[Frame_GoldenVMIP] [varchar](max) NULL,
	[PCSideLoadImage] [varchar](max) NULL,
	[ObjectsExtRange] [varchar](max) NULL,
	[ObjectsIntRange] [varchar](max) NULL,
	[Analyticsversion] [varchar](max) NULL,
	[Mgmt1_VMname] [varchar](max) NULL,
	[Mgmt1_VMIP] [varchar](max) NULL,
	[Mgmt1_ImageName] [varchar](max) NULL,
	[Oracle1_7Image] [varchar](max) NULL,
	[Oracle1_8Image] [varchar](max) NULL,
	[Oracle1_9Image] [varchar](max) NULL,
	[WinTemplateIP] [varchar](max) NULL,
	[LinTemplateIP] [varchar](max) NULL,
	[XPlay2012IP] [varchar](max) NULL,
	[SplunkIP] [varchar](max) NULL,
	[SplunkName] [varchar](max) NULL,
	[SplunkImage] [varchar](max) NULL,
	[HostCount] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[QueueUUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


