USE [1ClickDemo]
GO

/****** Object:  Table [dbo].[DataUser]    Script Date: 15-10-2019 00:07:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DataUser](
	[QueueUUID] [nvarchar](100) NOT NULL,
	[BackupIndex] [int] NOT NULL,
	[SenderEmail] [varchar](max) NULL,
	[DateCreated] [datetime] NOT NULL,
	[Settings001_Value] [text] NULL,
	[Settings002_Value] [text] NULL,
	[Settings003_Value] [text] NULL,
	[Settings004_Value] [text] NULL,
	[Settings005_Value] [text] NULL,
	[Settings006_Value] [text] NULL,
	[Settings007_Value] [text] NULL,
	[Settings008_Value] [text] NULL,
	[Settings009_Value] [text] NULL,
	[Settings010_Value] [text] NULL,
	[Settings011_Value] [text] NULL,
	[Settings012_Value] [text] NULL,
	[Settings013_Value] [text] NULL,
	[Settings014_Value] [text] NULL,
	[Settings015_Value] [text] NULL,
	[Settings016_Value] [text] NULL,
	[Settings017_Value] [text] NULL,
	[Settings018_Value] [text] NULL,
	[Settings019_Value] [text] NULL,
	[Settings020_Value] [text] NULL,
	[Settings001_Path] [text] NULL,
	[Settings002_Path] [text] NULL,
	[Settings003_Path] [text] NULL,
	[Settings004_Path] [text] NULL,
	[Settings005_Path] [text] NULL,
	[Settings006_Path] [text] NULL,
	[Settings007_Path] [text] NULL,
	[Settings008_Path] [text] NULL,
	[Settings009_Path] [text] NULL,
	[Settings010_Path] [text] NULL,
	[Settings011_Path] [text] NULL,
	[Settings012_Path] [text] NULL,
	[Settings013_Path] [text] NULL,
	[Settings014_Path] [text] NULL,
	[Settings015_Path] [text] NULL,
	[Settings016_Path] [text] NULL,
	[Settings017_Path] [text] NULL,
	[Settings018_Path] [text] NULL,
	[Settings019_Path] [text] NULL,
	[Settings020_Path] [text] NULL,
	[BluePrint001_Name] [text] NULL,
	[BluePrint002_Name] [text] NULL,
	[BluePrint003_Name] [text] NULL,
	[BluePrint004_Name] [text] NULL,
	[BluePrint005_Name] [text] NULL,
	[BluePrint006_Name] [text] NULL,
	[BluePrint007_Name] [text] NULL,
	[BluePrint008_Name] [text] NULL,
	[BluePrint009_Name] [text] NULL,
	[BluePrint010_Name] [text] NULL,
	[BluePrint011_Name] [text] NULL,
	[BluePrint012_Name] [text] NULL,
	[BluePrint013_Name] [text] NULL,
	[BluePrint014_Name] [text] NULL,
	[BluePrint015_Name] [text] NULL,
	[BluePrint016_Name] [text] NULL,
	[BluePrint017_Name] [text] NULL,
	[BluePrint018_Name] [text] NULL,
	[BluePrint019_Name] [text] NULL,
	[BluePrint020_Name] [text] NULL,
	[BluePrint021_Name] [text] NULL,
	[BluePrint022_Name] [text] NULL,
	[BluePrint023_Name] [text] NULL,
	[BluePrint024_Name] [text] NULL,
	[BluePrint025_Name] [text] NULL,
	[BluePrint026_Name] [text] NULL,
	[BluePrint027_Name] [text] NULL,
	[BluePrint028_Name] [text] NULL,
	[BluePrint029_Name] [text] NULL,
	[BluePrint030_Name] [text] NULL,
	[BluePrint031_Name] [text] NULL,
	[BluePrint032_Name] [text] NULL,
	[BluePrint033_Name] [text] NULL,
	[BluePrint034_Name] [text] NULL,
	[BluePrint035_Name] [text] NULL,
	[BluePrint036_Name] [text] NULL,
	[BluePrint037_Name] [text] NULL,
	[BluePrint038_Name] [text] NULL,
	[BluePrint039_Name] [text] NULL,
	[BluePrint040_Name] [text] NULL,
	[BluePrint041_Name] [text] NULL,
	[BluePrint042_Name] [text] NULL,
	[BluePrint043_Name] [text] NULL,
	[BluePrint044_Name] [text] NULL,
	[BluePrint045_Name] [text] NULL,
	[BluePrint046_Name] [text] NULL,
	[BluePrint047_Name] [text] NULL,
	[BluePrint048_Name] [text] NULL,
	[BluePrint049_Name] [text] NULL,
	[BluePrint050_Name] [text] NULL,
	[BluePrint001_JSON] [text] NULL,
	[BluePrint002_JSON] [text] NULL,
	[BluePrint003_JSON] [text] NULL,
	[BluePrint004_JSON] [text] NULL,
	[BluePrint005_JSON] [text] NULL,
	[BluePrint006_JSON] [text] NULL,
	[BluePrint007_JSON] [text] NULL,
	[BluePrint008_JSON] [text] NULL,
	[BluePrint009_JSON] [text] NULL,
	[BluePrint010_JSON] [text] NULL,
	[BluePrint011_JSON] [text] NULL,
	[BluePrint012_JSON] [text] NULL,
	[BluePrint013_JSON] [text] NULL,
	[BluePrint014_JSON] [text] NULL,
	[BluePrint015_JSON] [text] NULL,
	[BluePrint016_JSON] [text] NULL,
	[BluePrint017_JSON] [text] NULL,
	[BluePrint018_JSON] [text] NULL,
	[BluePrint019_JSON] [text] NULL,
	[BluePrint020_JSON] [text] NULL,
	[BluePrint021_JSON] [text] NULL,
	[BluePrint022_JSON] [text] NULL,
	[BluePrint023_JSON] [text] NULL,
	[BluePrint024_JSON] [text] NULL,
	[BluePrint025_JSON] [text] NULL,
	[BluePrint026_JSON] [text] NULL,
	[BluePrint027_JSON] [text] NULL,
	[BluePrint028_JSON] [text] NULL,
	[BluePrint029_JSON] [text] NULL,
	[BluePrint030_JSON] [text] NULL,
	[BluePrint031_JSON] [text] NULL,
	[BluePrint032_JSON] [text] NULL,
	[BluePrint033_JSON] [text] NULL,
	[BluePrint034_JSON] [text] NULL,
	[BluePrint035_JSON] [text] NULL,
	[BluePrint036_JSON] [text] NULL,
	[BluePrint037_JSON] [text] NULL,
	[BluePrint038_JSON] [text] NULL,
	[BluePrint039_JSON] [text] NULL,
	[BluePrint040_JSON] [text] NULL,
	[BluePrint041_JSON] [text] NULL,
	[BluePrint042_JSON] [text] NULL,
	[BluePrint043_JSON] [text] NULL,
	[BluePrint044_JSON] [text] NULL,
	[BluePrint045_JSON] [text] NULL,
	[BluePrint046_JSON] [text] NULL,
	[BluePrint047_JSON] [text] NULL,
	[BluePrint048_JSON] [text] NULL,
	[BluePrint049_JSON] [text] NULL,
	[BluePrint050_JSON] [text] NULL,
 CONSTRAINT [PK_DataUser] PRIMARY KEY CLUSTERED 
(
	[QueueUUID] ASC,
	[BackupIndex] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


